### ISSUE TITLE
get taints and add them to the template

### ISSUE THREAD

**Issue by chbndrhnns** [ContainerSolutions/registry-tooling#10]
My k8s master had a taint applied that prevented your script from running on this node.

I added to the temporary file you create:
```
tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
```
This allows the pod to be scheduled on the master, as well.
